### ISSUE TITLE
break with bevy 0.6

### ISSUE THREAD

**Issue by pyweeker** [jeremychone-channel/rust-invaders#4]
hello, your example is interesting for beginners like me, but broke with bevy 0.6 , could you please fix it ?

**Comment by lufog** [comment]
> hello, your example is interesting for beginners like me, but broke with bevy 0.6 , could you please fix it ?

Right now, the code in this repository is the same as the code from [these videos](https://www.youtube.com/playlist?list=PL7r-PXl6ZPcCB_9zZFU0krBoGK3y5f5Vt), making changes to it will confuse people who follow the tutorial from those videos. Unless, of course, the author records a video of the migration process, and adds it to the playlist.
In any case, you can use [migration guide](https://bevyengine.org/learn/book/migration-guides/0.5-0.6/) to fix code yourself, it's not very hard.

**Comment by pyweeker** [comment]
Hi, i have started fixing it for 0.6 but i am stuck now

https://github.com/pyweeker/rust-invaders/blob/main/README.md

**Comment by lufog** [comment]
@pyweeker I believe, they changed math library, new one can't cast Vec3 to Vec2. You can use something like this:
```let laser_scale = Vec2::new(laser_tf.scale.x, laser_tf.scale.y)``` 
Or 
```let laser_scale = (laser_tf.scale.x, laser_tf.scale.y).to_vec2()```...

**Comment by pyweeker** [comment]
Me again , i fixed and it does now compile but i am not very skilled to understand the bug, need to contact maintainers ?
cargo run RUST_BACKTRACE=1   
==>
```
warning: unused variable: `materials`
   --> src/main.rs:126:6
    |
126 |     mut materials: ResMut<Assets<ColorMaterial>>,
    |         ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_materials`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: variable does not need to be mutable
   --> src/main.rs:126:2
    |
126 |     mut materials: ResMut<Assets<ColorMaterial>>,
    |     ----^^^^^^^^^
    |     |
    |     help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: field is never read: `group_id`
  --> src/enemy.rs:21:2
   |
21 |     group_id: u32,
   |     ^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `rust-invaders` (bin "rust-invaders") generated 3 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/rust-invaders RUST_BACKTRACE=1`
2022-01-12T19:53:00.408206Z  WARN winit::platform_impl::platform::x11::util::randr: XRandR reported that the display's 0mm in size, which is certifiably insane    
2022-01-12T19:53:00.408897Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

2022-01-12T19:53:00.497995Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 2060", vendor: 4318, device: 7957, device_type: DiscreteGpu, backend: Vulkan }
thread 'Compute Task Pool (0)' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:229:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', /home/Me/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
```

**Comment by lufog** [comment]
@pyweeker, since migrating for newbies _(which I am myself)_ proved to be more difficult than I thought, I decided to make a pull request with all the changes.

**Comment by lufog** [comment]
@pyweeker, here is a pull request #5.

**Comment by pyweeker** [comment]
thanks

Le mer. 12 janv. 2022 à 23:52, Aleksey Smirnov ***@***.***> a
écrit :

**Comment by jeremychone** [comment]
Hi All, sorry for the delay, I have fixed it now, since today's commit.
